# Site settings
title: Amin N Ali
description: Analytics Expert & AI Enthusiast
lang: en-US
timezone: America/Los_Angeles

# Profile settings
author:
  name: Amin N Ali
  bio: Analytics expert & AI enthusiast
  image: /assets/profile.jpg
  icon: /assets/favicon.ico
  em_icon: /assets/i8-mail.svg
  email: mail[at]aminnali[dot]net
  li_icon: /assets/i8-linkedin.svg
  tw_icon: /assets/i8-x.svg
  md_icon: /assets/i8-mastodon.svg
  ig_icon: /assets/i8-instagram.svg
  sp_icon: /assets/i8-music.svg
  linkedin: https://www.linkedin.com/in/aminnali/
  twitter: https://x.com/aminn004
  mastodon: https://mathstodon.xyz/@aminn04
  instagram: https://instagram.com/aminn04
  spotify: https://open.spotify.com/user/aminn04
  

# URL settings
url: 
baseurl: /

# Build settings
theme: minima
sass:
  style: compressed
plugins:
  # - jekyll-feed
  - jekyll-sitemap
  - jekyll-email-protect

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - .vscode/
  - .github/
